BINARY_NAME=cq
PKG=github.com/gnikyt/cq/v2

.PHONY: all build test test-coverage test-race bench docs clean

all: clean build test

build:
	mkdir -p ./dist
	go build -o ./dist/${BINARY_NAME} ${PKG}

test:
	go test -timeout 30s ${PKG}

test-coverage:
	go test -timeout 30s -coverprofile=/tmp/${BINARY_NAME}-cover ${PKG}

test-race:
	go test -timeout 30s -race ${PKG}

bench:
	go test -benchmem -bench=. -benchtime=2x ${PKG}

# Docs are generated by onedoc (https://github.com/gnikyt/onedoc).
# Local dev uses a sibling checkout at ../onedoc. Once onedoc is published+tagged,
# swap this for: go run github.com/gnikyt/onedoc/cmd/onedoc@latest -config docs/onedoc.json
docs:
	cd ../onedoc && go run ./cmd/onedoc -config "$(CURDIR)/docs/onedoc.json"

clean:
	go clean
	rm /tmp/${BINARY_NAME}-cover &2> /dev/null
	rm ./dist/${BINARY_NAME} &2> /dev/null
